			<h1>Qui suis-je ?</h1>
			<p style="text-indent: 15px;">	Pour vous parler un peu de moi et de mon parcours professionnel, je m'appelle Patricia Balingon, marié et maman de trois enfants .J'ai effectué mes études de couture au lycée professionnel de Peruwelz, en Belgique, cursus que je stoppe en 1982 pour aller travailler. Je trouve un emploi un mois après comme débutante dans un atelier de couture, en bas de chaine, à couper les fils des blousons. Je ne suis pas une personne qui baisse les bras aussi facilement. À force de persévérance, d'heure supplémentaire et avec les conseils de ma patronne, je passe par tous les poste de l'usine (surfilage, machine simple, double aiguille, entoilage, repassage), pour finir comme chef d'atelier à l'âge de 27 ans.</p>

<p style="text-indent: 15px;">Les années passent, je me marie, fonde une famille, l'usine où je travaille ferme ses portes, par la suite, je travaille à la maison comme retoucheuse pour un magasin de prêt à porter tout en vendant quelque une de mes créations.</p>

<p style="text-indent: 15px;">Lorsque mon dernier rentre à l'école maternel, je décide de trouver un emploi plus stable, grâce à une amie c'est chose faite, un poste de créatrice en déguisement dans un magasin du même thème. Mon patron étant délégué de Miss Nord Pas-de-Calais, j'ai eu la chance de travailler pour TF1 à la création de tableaux pour les élections de Miss france, ainsi qu'a la création des robes régional de Miss Nord Pas-de-Calais et de Miss Picardie. J'ai aussi eu l'occasion de faire la tenue de French cancan pour la première dauphine lors des éléctions Miss World, ainsi qu'énormément d'autres créations toutes plus particulière les unes que les autres.</p>

<p style="text-indent: 15px;">15 Ans passe, je change de situation familiale, d'emploi et de département, direction le Pas-de-Calais, Loos en Gohelle. Je me lance en tant qu'auto entrepreneuse dans la création et les retouches,"À l'atelier de couture" et née. Je travaille dans un premier temps pour un cabaret (tenue french cancan, tenue de russe, tenue ombre chinoise, tenue égyptienne et tenue de clôture).</p>

	<p style="text-indent: 15px;">Plusieurs années on passée et ce métier passionnant m'exalte toujours autant, alors pourquoi ne pas partager mon expérience et mon savoir dans la bonne humeur et la joie avec Vous ? </p>